# Generated by Django 6.0.5 on 2026-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_job_type_job_salary_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
    ]
