# Generated by Django 6.0.5 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('design', 'Design'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('sales', 'Sales'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
