# Generated by Django 6.0.5 on 2026-06-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_saved_jobs_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
