# Generated by Django 6.0.5 on 2026-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_views_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='ETB', max_length=3),
        ),
    ]
