"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv  # type: ignore
except Exception:
    load_dotenv = None

if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")

def env(name: str, default: str | None = None) -> str | None:
    value = os.environ.get(name)
    return value if value is not None else default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", "django-insecure-change-me")  # type: ignore[assignment]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (env("DJANGO_DEBUG", "1") == "1")

if env("DJANGO_ALLOWED_HOSTS"):
    ALLOWED_HOSTS = [h.strip() for h in (env("DJANGO_ALLOWED_HOSTS", "") or "").split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"] if DEBUG else []

if DEBUG and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',           # Django REST Framework
    'rest_framework.authtoken', # Token authentication (creates authtoken_token table)
    # Local apps
    'accounts',
    'jobs',
]

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:profile"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves compressed static files efficiently in production.
    # Must be placed immediately after SecurityMiddleware.
    # In Docker, Nginx handles /static/ directly, but Whitenoise is the
    # fallback when running without Nginx (e.g. Railway, Render one-dyno setups).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Injects `saved_jobs_count` into every template (navbar badge)
                'jobs.context_processors.saved_jobs_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = env("DB_ENGINE", "sqlite")
if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", "jobboard"),
            "USER": env("DB_USER", "postgres"),
            "PASSWORD": env("DB_PASSWORD", ""),
            "HOST": env("DB_HOST", "127.0.0.1"),
            "PORT": env("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Session Configuration for Security & UX
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 2 weeks in seconds
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing session cookie
SESSION_COOKIE_SECURE = (not DEBUG)  # Only send cookie over HTTPS in production
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Clear session on browser close (optional)
SESSION_SAVE_EVERY_REQUEST = False  # Only save on changes for performance


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
# STATIC_ROOT: where `collectstatic` writes files — served by Nginx / Whitenoise.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise: serve compressed static files with long-lived browser cache headers.
# CompressedManifestStaticFilesStorage requires `collectstatic` to have run, so
# we only enable it in production (DEBUG=False). Tests and the dev server use the
# plain default, which doesn't need a manifest file.
if DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# Media files (user uploads: resumes, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ── Reverse-proxy trust (Nginx → Gunicorn) ────────────────────────────────────
# Tell Django to trust the X-Forwarded-For and X-Forwarded-Proto headers
# set by Nginx. Without this, request.is_secure() and CSRF checks break
# when the app sits behind a proxy.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF trusted origins — required when DEBUG=False and requests come through Nginx.
# Add your production domain here when deploying.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
]
# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:profile"
LOGOUT_REDIRECT_URL = "jobs:home"

MESSAGE_TAGS = {
    message_constants.DEBUG: "secondary",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    message_constants.ERROR: "danger",
}

# ── Django REST Framework ───────────────────────────────────────────────────
#
# REST architecture:
#   A client (mobile app, frontend SPA, curl) sends an HTTP request.
#   DRF routes it through a ViewSet, which calls a Serializer to turn the
#   Django ORM object into JSON (or XML). Authentication is checked first.
#
# Authentication:
#   TokenAuthentication  → client sends  Authorization: Token <token>  header.
#   SessionAuthentication → used by the Browsable API in the browser (uses cookies).
#
# Permissions:
#   IsAuthenticatedOrReadOnly → read (GET) is public, write (POST/PUT/DELETE)
#   requires a valid token.
REST_FRAMEWORK = {
    # Authentication classes tried in order
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # browsable API
    ],
    # Default permission policy
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Pagination — returns 20 results per page with next/previous links
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Renderers — JSON + the interactive Browsable API HTML interface
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

# ── Email Configuration ───────────────────────────────────────────────────────
# How Django email works:
#   Development  → console backend prints emails to the terminal (no SMTP needed)
#   Production   → smtp backend delivers via EMAIL_HOST / EMAIL_PORT / credentials
#
# Switch by setting EMAIL_BACKEND in .env:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#
# send_mail() / EmailMultiAlternatives both use this backend automatically.

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",  # dev default
)
EMAIL_HOST          = env("EMAIL_HOST",          "smtp.gmail.com")
EMAIL_PORT          = int(env("EMAIL_PORT",      "587"))
EMAIL_USE_TLS       = (env("EMAIL_USE_TLS",      "1") == "1")
EMAIL_HOST_USER     = env("EMAIL_HOST_USER",     "")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL  = env("DEFAULT_FROM_EMAIL",  "JobBoard <noreply@jobboard.local>")
